# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "build-store"
client_id = "947ca87608fe5a0887768cfb94bb3101"
application_url = "https://accident-bd-terror-soap.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,write_assigned_fulfillment_orders,read_assigned_fulfillment_orders,read_customer_events,write_checkout_branding_settings,read_checkout_branding_settings,write_custom_pixels,read_custom_pixels,write_customers,read_customers,write_discounts,read_discounts,write_discovery,read_discovery,write_draft_orders,read_draft_orders,write_files,read_files,write_fulfillments,read_fulfillments,read_gdpr_data_request,write_gift_cards,read_gift_cards,write_inventory,read_inventory,write_legal_policies,read_legal_policies,write_locations,read_locations,write_marketing_events,read_marketing_events,write_merchant_managed_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_metaobject_definitions,read_metaobject_definitions,write_online_store_navigation,read_online_store_navigation,write_metaobjects,read_metaobjects,write_order_edits,read_order_edits,write_online_store_pages,read_online_store_pages,write_orders,read_orders,write_packing_slip_templates,read_packing_slip_templates,write_payment_customizations,read_payment_customizations,write_payment_terms,read_payment_terms,write_pixels,read_pixels,write_price_rules,read_price_rules,write_product_feeds,read_product_feeds,write_product_listings,read_product_listings,write_products,read_products,write_publications,read_publications,write_purchase_options,read_purchase_options,write_reports,read_reports,write_resource_feedbacks,read_resource_feedbacks,write_returns,read_returns,write_channels,read_channels,write_script_tags,read_script_tags,write_shipping,read_shipping,write_locales,read_locales,write_markets,read_markets,read_shopify_payments_accounts,read_shopify_payments_bank_accounts,read_shopify_payments_disputes,read_shopify_payments_payouts,write_content,read_content,write_themes,read_themes,write_third_party_fulfillment_orders,read_third_party_fulfillment_orders,write_translations,read_translations,read_all_cart_transforms,write_cart_transforms,read_cart_transforms,write_companies,read_companies,write_custom_fulfillment_services,read_custom_fulfillment_services,write_customer_merge,read_customer_merge,write_delivery_customizations,read_delivery_customizations,write_fulfillment_constraint_rules,read_fulfillment_constraint_rules,write_gates,read_gates"

[auth]
redirect_urls = [
  "https://accident-bd-terror-soap.trycloudflare.com/auth/callback",
  "https://accident-bd-terror-soap.trycloudflare.com/auth/shopify/callback",
  "https://accident-bd-terror-soap.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "renergii.myshopify.com"
